"""create_application_tables

Revision ID: 2eb32034c41c
Revises: 3e5cdfa4a48e
Create Date: 2026-03-17 03:30:28.279313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eb32034c41c'
down_revision: Union[str, Sequence[str], None] = '3e5cdfa4a48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('diabetic_drug_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('drug_class', sa.String(length=100), nullable=True),
    sa.Column('base_risk_level', sa.String(length=50), nullable=False),
    sa.Column('risk_with_nephropathy', sa.String(length=50), nullable=True),
    sa.Column('risk_with_cardiovascular', sa.String(length=50), nullable=True),
    sa.Column('risk_with_hypoglycemia_prone', sa.String(length=50), nullable=True),
    sa.Column('contraindicated_if_egfr_below', sa.Float(), nullable=True),
    sa.Column('caution_if_egfr_below', sa.Float(), nullable=True),
    sa.Column('contraindicated_if_potassium_above', sa.Float(), nullable=True),
    sa.Column('affects_blood_glucose', sa.Boolean(), nullable=True),
    sa.Column('glucose_effect', sa.String(length=50), nullable=True),
    sa.Column('masks_hypoglycemia', sa.Boolean(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('monitoring_guidance', sa.Text(), nullable=True),
    sa.Column('dose_adjustment_guidance', sa.Text(), nullable=True),
    sa.Column('safer_alternatives', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diabetic_drug_rules_drug_name'), 'diabetic_drug_rules', ['drug_name'], unique=False)
    op.create_index(op.f('ix_diabetic_drug_rules_id'), 'diabetic_drug_rules', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diabetic_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('diabetes_type', sa.String(length=50), nullable=True),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=True),
    sa.Column('years_with_diabetes', sa.Integer(), nullable=True),
    sa.Column('hba1c', sa.Float(), nullable=True),
    sa.Column('fasting_glucose', sa.Float(), nullable=True),
    sa.Column('postprandial_glucose', sa.Float(), nullable=True),
    sa.Column('mean_blood_glucose', sa.Float(), nullable=True),
    sa.Column('egfr', sa.Float(), nullable=True),
    sa.Column('creatinine', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('ast', sa.Float(), nullable=True),
    sa.Column('total_cholesterol', sa.Float(), nullable=True),
    sa.Column('triglycerides', sa.Float(), nullable=True),
    sa.Column('hdl_cholesterol', sa.Float(), nullable=True),
    sa.Column('ldl_cholesterol', sa.Float(), nullable=True),
    sa.Column('vldl_cholesterol', sa.Float(), nullable=True),
    sa.Column('has_nephropathy', sa.Boolean(), nullable=True),
    sa.Column('has_retinopathy', sa.Boolean(), nullable=True),
    sa.Column('has_neuropathy', sa.Boolean(), nullable=True),
    sa.Column('has_cardiovascular', sa.Boolean(), nullable=True),
    sa.Column('has_hypertension', sa.Boolean(), nullable=True),
    sa.Column('has_hyperlipidemia', sa.Boolean(), nullable=True),
    sa.Column('has_obesity', sa.Boolean(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('comorbidities', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diabetic_patients_id'), 'diabetic_patients', ['id'], unique=False)
    op.create_index(op.f('ix_diabetic_patients_patient_id'), 'diabetic_patients', ['patient_id'], unique=True)
    op.create_index(op.f('ix_diabetic_patients_user_id'), 'diabetic_patients', ['user_id'], unique=False)
    op.create_table('drugs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drugbank_id', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('brand_names', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('drug_class', sa.String(length=255), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('pharmacology', sa.Text(), nullable=True),
    sa.Column('molecular_formula', sa.String(length=100), nullable=True),
    sa.Column('molecular_weight', sa.Float(), nullable=True),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drugs_drugbank_id'), 'drugs', ['drugbank_id'], unique=True)
    op.create_index(op.f('ix_drugs_generic_name'), 'drugs', ['generic_name'], unique=False)
    op.create_index(op.f('ix_drugs_id'), 'drugs', ['id'], unique=False)
    op.create_index(op.f('ix_drugs_name'), 'drugs', ['name'], unique=False)
    op.create_table('medication_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('time_of_day', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medication_schedules_id'), 'medication_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_medication_schedules_user_id'), 'medication_schedules', ['user_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('auc_roc', sa.Float(), nullable=True),
    sa.Column('training_samples', sa.Integer(), nullable=True),
    sa.Column('test_samples', sa.Integer(), nullable=True),
    sa.Column('n_features', sa.Integer(), nullable=True),
    sa.Column('hyperparameters', sa.Text(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_id'), 'model_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_model_metrics_model_type'), 'model_metrics', ['model_type'], unique=False)
    op.create_table('offsides_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('raw_row', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offsides_effects_created_at'), 'offsides_effects', ['created_at'], unique=False)
    op.create_index(op.f('ix_offsides_effects_drug_name'), 'offsides_effects', ['drug_name'], unique=False)
    op.create_index(op.f('ix_offsides_effects_id'), 'offsides_effects', ['id'], unique=False)
    op.create_index(op.f('ix_offsides_effects_severity'), 'offsides_effects', ['severity'], unique=False)
    op.create_table('optimization_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('optimization_method', sa.String(length=50), nullable=False),
    sa.Column('best_score', sa.Float(), nullable=False),
    sa.Column('best_params', sa.Text(), nullable=True),
    sa.Column('n_trials', sa.Integer(), nullable=True),
    sa.Column('total_time_seconds', sa.Float(), nullable=True),
    sa.Column('trial_history', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_results_id'), 'optimization_results', ['id'], unique=False)
    op.create_index(op.f('ix_optimization_results_model_type'), 'optimization_results', ['model_type'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('vision_model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('chroma_collection_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_id'), 'prescriptions', ['id'], unique=False)
    op.create_index(op.f('ix_prescriptions_user_id'), 'prescriptions', ['user_id'], unique=False)
    op.create_table('tracked_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_jobs_created_at'), 'tracked_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracked_jobs_id'), 'tracked_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_tracked_jobs_name'), 'tracked_jobs', ['name'], unique=False)
    op.create_index(op.f('ix_tracked_jobs_status'), 'tracked_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_tracked_jobs_updated_at'), 'tracked_jobs', ['updated_at'], unique=False)
    op.create_table('twosides_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug1_name', sa.String(length=255), nullable=False),
    sa.Column('drug2_name', sa.String(length=255), nullable=False),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('raw_row', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_twosides_interactions_created_at'), 'twosides_interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_twosides_interactions_drug1_name'), 'twosides_interactions', ['drug1_name'], unique=False)
    op.create_index(op.f('ix_twosides_interactions_drug2_name'), 'twosides_interactions', ['drug2_name'], unique=False)
    op.create_index(op.f('ix_twosides_interactions_id'), 'twosides_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_twosides_interactions_severity'), 'twosides_interactions', ['severity'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('adherence_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['medication_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adherence_logs_id'), 'adherence_logs', ['id'], unique=False)
    op.create_index(op.f('ix_adherence_logs_logged_at'), 'adherence_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_adherence_logs_schedule_id'), 'adherence_logs', ['schedule_id'], unique=False)
    op.create_table('comparison_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug1_name', sa.String(length=255), nullable=False),
    sa.Column('drug2_name', sa.String(length=255), nullable=False),
    sa.Column('drug1_id', sa.Integer(), nullable=True),
    sa.Column('drug2_id', sa.Integer(), nullable=True),
    sa.Column('has_interaction', sa.Boolean(), nullable=True),
    sa.Column('is_safe', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('safety_message', sa.Text(), nullable=True),
    sa.Column('ml_probability', sa.Float(), nullable=True),
    sa.Column('ml_severity', sa.String(length=50), nullable=True),
    sa.Column('ml_decision_source', sa.String(length=50), nullable=True),
    sa.Column('ml_model_version', sa.String(length=100), nullable=True),
    sa.Column('rule_override_reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drug1_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['drug2_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_logs_drug1_name'), 'comparison_logs', ['drug1_name'], unique=False)
    op.create_index(op.f('ix_comparison_logs_drug2_name'), 'comparison_logs', ['drug2_name'], unique=False)
    op.create_index(op.f('ix_comparison_logs_id'), 'comparison_logs', ['id'], unique=False)
    op.create_index(op.f('ix_comparison_logs_timestamp'), 'comparison_logs', ['timestamp'], unique=False)
    op.create_table('diabetic_drug_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('contraindication_reason', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('alternative_drugs', sa.Text(), nullable=True),
    sa.Column('monitoring_required', sa.Text(), nullable=True),
    sa.Column('interacting_medications', sa.Text(), nullable=True),
    sa.Column('interaction_severity', sa.String(length=50), nullable=True),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('labs_at_assessment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['diabetic_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diabetic_drug_risks_id'), 'diabetic_drug_risks', ['id'], unique=False)
    op.create_table('diabetic_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=True),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('drug_class', sa.String(length=100), nullable=True),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('indication', sa.String(length=255), nullable=True),
    sa.Column('is_diabetes_medication', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['diabetic_patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diabetic_medications_id'), 'diabetic_medications', ['id'], unique=False)
    op.create_table('drug_categories',
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('drug_id', 'category_id')
    )
    op.create_table('drug_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug1_id', sa.Integer(), nullable=False),
    sa.Column('drug2_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('management', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('evidence_level', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drug1_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['drug2_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_interactions_drug1_id'), 'drug_interactions', ['drug1_id'], unique=False)
    op.create_index(op.f('ix_drug_interactions_drug2_id'), 'drug_interactions', ['drug2_id'], unique=False)
    op.create_index(op.f('ix_drug_interactions_id'), 'drug_interactions', ['id'], unique=False)
    op.create_table('drug_similarities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug1_id', sa.Integer(), nullable=False),
    sa.Column('drug2_id', sa.Integer(), nullable=False),
    sa.Column('structural_similarity', sa.Float(), nullable=True),
    sa.Column('therapeutic_similarity', sa.Float(), nullable=True),
    sa.Column('overall_similarity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['drug1_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['drug2_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_similarities_drug1_id'), 'drug_similarities', ['drug1_id'], unique=False)
    op.create_index(op.f('ix_drug_similarities_drug2_id'), 'drug_similarities', ['drug2_id'], unique=False)
    op.create_index(op.f('ix_drug_similarities_id'), 'drug_similarities', ['id'], unique=False)
    op.create_table('ml_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drug1_name', sa.String(length=255), nullable=False),
    sa.Column('drug2_name', sa.String(length=255), nullable=False),
    sa.Column('drug1_id', sa.Integer(), nullable=True),
    sa.Column('drug2_id', sa.Integer(), nullable=True),
    sa.Column('interaction_probability', sa.Float(), nullable=False),
    sa.Column('predicted_interaction', sa.Boolean(), nullable=True),
    sa.Column('severity_prediction', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_predictions', sa.Text(), nullable=True),
    sa.Column('actual_interaction', sa.Boolean(), nullable=True),
    sa.Column('prediction_correct', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drug1_id'], ['drugs.id'], ),
    sa.ForeignKeyConstraint(['drug2_id'], ['drugs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_predictions_drug1_name'), 'ml_predictions', ['drug1_name'], unique=False)
    op.create_index(op.f('ix_ml_predictions_drug2_name'), 'ml_predictions', ['drug2_name'], unique=False)
    op.create_index(op.f('ix_ml_predictions_id'), 'ml_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ml_predictions_timestamp'), 'ml_predictions', ['timestamp'], unique=False)
    op.create_table('prescription_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieved_context', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_chats_id'), 'prescription_chats', ['id'], unique=False)
    op.create_table('prescription_medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('dosage', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('morning', sa.Boolean(), nullable=True),
    sa.Column('afternoon', sa.Boolean(), nullable=True),
    sa.Column('evening', sa.Boolean(), nullable=True),
    sa.Column('night', sa.Boolean(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_medicines_id'), 'prescription_medicines', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_revoked_at'), 'refresh_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_prescription_medicines_id'), table_name='prescription_medicines')
    op.drop_table('prescription_medicines')
    op.drop_index(op.f('ix_prescription_chats_id'), table_name='prescription_chats')
    op.drop_table('prescription_chats')
    op.drop_index(op.f('ix_ml_predictions_timestamp'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_id'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_drug2_name'), table_name='ml_predictions')
    op.drop_index(op.f('ix_ml_predictions_drug1_name'), table_name='ml_predictions')
    op.drop_table('ml_predictions')
    op.drop_index(op.f('ix_drug_similarities_id'), table_name='drug_similarities')
    op.drop_index(op.f('ix_drug_similarities_drug2_id'), table_name='drug_similarities')
    op.drop_index(op.f('ix_drug_similarities_drug1_id'), table_name='drug_similarities')
    op.drop_table('drug_similarities')
    op.drop_index(op.f('ix_drug_interactions_id'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_drug2_id'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_drug1_id'), table_name='drug_interactions')
    op.drop_table('drug_interactions')
    op.drop_table('drug_categories')
    op.drop_index(op.f('ix_diabetic_medications_id'), table_name='diabetic_medications')
    op.drop_table('diabetic_medications')
    op.drop_index(op.f('ix_diabetic_drug_risks_id'), table_name='diabetic_drug_risks')
    op.drop_table('diabetic_drug_risks')
    op.drop_index(op.f('ix_comparison_logs_timestamp'), table_name='comparison_logs')
    op.drop_index(op.f('ix_comparison_logs_id'), table_name='comparison_logs')
    op.drop_index(op.f('ix_comparison_logs_drug2_name'), table_name='comparison_logs')
    op.drop_index(op.f('ix_comparison_logs_drug1_name'), table_name='comparison_logs')
    op.drop_table('comparison_logs')
    op.drop_index(op.f('ix_adherence_logs_schedule_id'), table_name='adherence_logs')
    op.drop_index(op.f('ix_adherence_logs_logged_at'), table_name='adherence_logs')
    op.drop_index(op.f('ix_adherence_logs_id'), table_name='adherence_logs')
    op.drop_table('adherence_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_twosides_interactions_severity'), table_name='twosides_interactions')
    op.drop_index(op.f('ix_twosides_interactions_id'), table_name='twosides_interactions')
    op.drop_index(op.f('ix_twosides_interactions_drug2_name'), table_name='twosides_interactions')
    op.drop_index(op.f('ix_twosides_interactions_drug1_name'), table_name='twosides_interactions')
    op.drop_index(op.f('ix_twosides_interactions_created_at'), table_name='twosides_interactions')
    op.drop_table('twosides_interactions')
    op.drop_index(op.f('ix_tracked_jobs_updated_at'), table_name='tracked_jobs')
    op.drop_index(op.f('ix_tracked_jobs_status'), table_name='tracked_jobs')
    op.drop_index(op.f('ix_tracked_jobs_name'), table_name='tracked_jobs')
    op.drop_index(op.f('ix_tracked_jobs_id'), table_name='tracked_jobs')
    op.drop_index(op.f('ix_tracked_jobs_created_at'), table_name='tracked_jobs')
    op.drop_table('tracked_jobs')
    op.drop_index(op.f('ix_prescriptions_user_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_optimization_results_model_type'), table_name='optimization_results')
    op.drop_index(op.f('ix_optimization_results_id'), table_name='optimization_results')
    op.drop_table('optimization_results')
    op.drop_index(op.f('ix_offsides_effects_severity'), table_name='offsides_effects')
    op.drop_index(op.f('ix_offsides_effects_id'), table_name='offsides_effects')
    op.drop_index(op.f('ix_offsides_effects_drug_name'), table_name='offsides_effects')
    op.drop_index(op.f('ix_offsides_effects_created_at'), table_name='offsides_effects')
    op.drop_table('offsides_effects')
    op.drop_index(op.f('ix_model_metrics_model_type'), table_name='model_metrics')
    op.drop_index(op.f('ix_model_metrics_id'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_medication_schedules_user_id'), table_name='medication_schedules')
    op.drop_index(op.f('ix_medication_schedules_id'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    op.drop_index(op.f('ix_drugs_name'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_id'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_generic_name'), table_name='drugs')
    op.drop_index(op.f('ix_drugs_drugbank_id'), table_name='drugs')
    op.drop_table('drugs')
    op.drop_index(op.f('ix_diabetic_patients_user_id'), table_name='diabetic_patients')
    op.drop_index(op.f('ix_diabetic_patients_patient_id'), table_name='diabetic_patients')
    op.drop_index(op.f('ix_diabetic_patients_id'), table_name='diabetic_patients')
    op.drop_table('diabetic_patients')
    op.drop_index(op.f('ix_diabetic_drug_rules_id'), table_name='diabetic_drug_rules')
    op.drop_index(op.f('ix_diabetic_drug_rules_drug_name'), table_name='diabetic_drug_rules')
    op.drop_table('diabetic_drug_rules')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
